      SUBROUTINE  TSOL(Y,BK,R,EM,WN)
      REAL*8  BK,R,EM,XB,WN,PHIB1,PHIB2,PSIB1,PSIB2,Y
      DIMENSION  Y(6,3)
C
C      SOLUTION FOR HOMOGENEOUS SPHERE
C      TORSIONAL OSCILLATION
C      SUBROUTINE REQUIRED - SPHERF
C
      XB=BK*R*R
      CALL  SPHERF(PHIB1,PHIB2,PSIB1,PSIB2,WN,XB,20)
      Y(1,1)=PHIB1
      Y(2,1)=EM*((WN-1.0D+0)*PHIB1-(XB*PHIB2)/(2.0D+0*WN+3.0D+0))
      RETURN
      END
